- type: job
  id: CommanderCriticalThreats
  name: job-name-cct
  description: job-description-cct
  playTimeTracker: JobCommanderCriticalThreats
  department: Command
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 18000 # 5 hrs
  startingGear: CommanderCriticalThreatsGear
  icon: JobIconNanotrasenCCT
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
    - AllAccess
  access:
    - CentralCommand
  special:
    - !type:AddImplantSpecial
        implants: [ MindShieldImplant ]
    - !type:AddComponentSpecial
        components:
          - type: CommandStaff

- type: startingGear
  id: CommanderCriticalThreatsGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: CommanderPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetCentCom
    pocket1: WeaponPistolN1984
  storage:
    back:
      - Flash
      - MagazinePistol
